clusterInfrastructure:
  provider: "kind"
clusterSecurity:
  policyEngine: "kyverno"
clusterIngress:
  domain: "educates.example.com"
  tlsCertificateRef:
    namespace: "educates-secrets"
    name: "educates-example-com-fromcache-tls"
  caCertificateRef:
    namespace: "educates-secrets"
    name: "educates-example-com-fromcache-ca"
