#@ load("@ytt:data", "data")

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: secrets-manager
  namespace: #@ data.values.operator.namespace
  annotations:
    kapp.k14s.io/change-group: secrets.educates.dev/service-accounts
    #! Following currently needed for kapp on OpenShift.
    #! TODO: Bring kapp rebaseRules for Openshift service accounts
#!    kapp.k14s.io/create-strategy: fallback-on-update
#!    kapp.k14s.io/update-strategy: skip
