#@ load("@ytt:data", "data")

#@ def image_reference(name):
#@   registry = data.values.imageRegistry.host
#@   if not registry:
#@     registry = "localhost:5001"
#@   end
#@   if data.values.imageRegistry.namespace:
#@     registry = "{}/{}".format(registry, data.values.imageRegistry.namespace)
#@   end
#@   return "{}/educates-{}:{}".format(registry, name, data.values.version)
#@ end

---
imageVersions:
  - name: session-manager
    image: #@ image_reference("session-manager")
  - name: training-portal
    image: #@ image_reference("training-portal")
  - name: docker-registry
    image: #@ image_reference("docker-registry")
  - name: pause-container
    image: #@ image_reference("pause-container")
  - name: base-environment
    image: #@ image_reference("base-environment")
  - name: jdk8-environment
    image: #@ image_reference("jdk8-environment")
  - name: jdk11-environment
    image: #@ image_reference("jdk11-environment")
  - name: jdk17-environment
    image: #@ image_reference("jdk17-environment")
  - name: jdk21-environment
    image: #@ image_reference("jdk21-environment")
  - name: conda-environment
    image: #@ image_reference("conda-environment")
  - name: secrets-manager
    image: #@ image_reference("secrets-manager")
  - name: tunnel-manager
    image: #@ image_reference("tunnel-manager")
  - name: image-cache
    image: #@ image_reference("image-cache")
  - name: assets-server
    image: #@ image_reference("assets-server")
  - name: debian-base-image
    image: "debian:sid-20230502-slim"
  - name: docker-in-docker
    image: "docker:20.10.18-dind"
  - name: rancher-k3s-v1.25
    image: "rancher/k3s:v1.25.16-k3s4"
  - name: rancher-k3s-v1.26
    image: "rancher/k3s:v1.26.12-k3s1"
  - name: rancher-k3s-v1.27
    image: "rancher/k3s:v1.27.9-k3s1"
  - name: rancher-k3s-v1.28
    image: "rancher/k3s:v1.28.5-k3s1"
  - name: loftsh-vcluster
    image: "loftsh/vcluster:0.18.1"
  - name: contour-bundle
    #! contour.community.tanzu.vmware.com.1.22.0
    image: "projects.registry.vmware.com/tce/contour@sha256:b68ad8ec3012db7d2a2e84f8544685012e2dca09d28d54dce8735fb60f0d05bf"
