#@ load("@ytt:data", "data")
#@ load("@ytt:yaml", "yaml")

#@ def bundle_reference():
#@   registry = data.values.imageRegistry.host
#@   if not registry or registry == "localhost:5001":
#@     registry = "registry.default.svc.cluster.local"
#@   end
#@   if data.values.imageRegistry.namespace:
#@     registry = "{}/{}".format(registry, data.values.imageRegistry.namespace)
#@   end
#@   return "{}/educates-installer:{}".format(registry, data.values.version)
#@ end

#! This configmap provides interoperability between the kapp-controller installation and 
#! the educates CLI installation, by preconfiguring the label kapp-controller's App will use to
#! be the same as the one used by the educates CLI.
#! The name of the configmap will be the same as the App, but with `.app` appended.
#! The `spec` needs `labelKey` and `labelValue` fields to be set.
---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    kapp.k14s.io/is-app: ""
  annotations:
    kapp.k14s.io/app-changes-use-app-label: ""
  name: installer.educates.dev.app
  namespace: educates-installer
data:
  spec: '{"labelKey":"installer","labelValue":"educates-installer.app"}'
---
apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: installer.educates.dev
  namespace: educates-installer
spec:
  serviceAccountName: educates-installer
  syncPeriod: 87600h #! 10 years
  fetch:
    - imgpkgBundle:
        image: #@ bundle_reference()
      path: bundle
    - inline:
        paths:
          disable-kapp-controller.yaml: |
            clusterPackages:
              kapp-controller:
                enabled: false
      path: values
  template:
    - ytt:
        valuesFrom:
          - path: "bundle/kbld/kbld-images.yaml"
          - secretRef:
              name: educates-installer
          - path: values/disable-kapp-controller.yaml
        paths:
          - "bundle/kbld/kbld-bundle.yaml"
          - "bundle/config/kapp"
          - "bundle/config/ytt"
    - kbld:
        paths:
          - "bundle/.imgpkg/images.yml"
          - "-"
  deploy:
    - kapp:
        rawOptions:
          - "--app-changes-max-to-keep=0"
          - "--diff-changes=true"
