#@ load("@ytt:overlay", "overlay")
#@ load("@ytt:data", "data")
#@ load("@ytt:yaml", "yaml")
---
apiVersion: v1
kind: Namespace
metadata:
  name: educates-config

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: educates-config
  namespace: educates-config
data:
  values.yaml: #@ yaml.encode(data.values)
