#@ load("@ytt:data", "data")
#@ load("@ytt:overlay", "overlay")
#@ load("functions.star", "isClusterPackageExplicitDisabled")

#! This removes settings for disabled packages

#@overlay/match-child-defaults missing_ok=True
clusterPackages:
  educates:
    #@ if isClusterPackageExplicitDisabled("educates"):
    #@overlay/replace
    enabled: false
    #@overlay/replace
    settings: {}
    #@ end