#@ load("@ytt:data", "data")
#@ load("@ytt:overlay", "overlay")
#@ load("/functions.star", "isGlobalCaCertificateRefEnabled")

#@overlay/match-child-defaults missing_ok=True
clusterPackages:
  certs:
    enabled: #@ isGlobalCaCertificateRefEnabled()
    #@ if isGlobalCaCertificateRefEnabled():
    settings:
      domains:
        -  #@ data.values.clusterIngress.domain
      certProvider: "local" #! TODO: This can be provided (provides the wildcard) or local (for rootCA)
      local:
        caCertificateRef:
          name: #@ data.values.clusterInfrastructure.caCertificateRef.name
          namespace: #@ data.values.clusterInfrastructure.caCertificateRef.namespace
      wildcardCertificateNamespace: #@ data.values.clusterInfrastructure.caCertificateRef.namespace
      certmanagerClusterResourceNamespace: #@ data.values.clusterInfrastructure.caCertificateRef.namespace
    #@ else:
    settings: {}
    #@ end