{{- $ns := include "educates.operator.namespace" . }}
{{- $domain := .Values.clusterIngress.domain }}
{{- $tlsRef := .Values.clusterIngress.tlsCertificateRef.name }}
{{- $tlsCert := index .Values.clusterIngress.tlsCertificate "tls.crt" }}
{{- $tlsKey := index .Values.clusterIngress.tlsCertificate "tls.key" }}
{{- if and (not $tlsRef) $tlsCert $tlsKey }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $domain }}-tls
  namespace: {{ $ns }}
  labels:
    app.kubernetes.io/name: {{ include "educates.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
type: kubernetes.io/tls
data:
  tls.crt: {{ $tlsCert | b64enc }}
  tls.key: {{ $tlsKey | b64enc }}
{{- end }}
{{- $caRef := .Values.clusterIngress.caCertificateRef.name }}
{{- $caCert := index .Values.clusterIngress.caCertificate "ca.crt" }}
{{- if and (not $caRef) $caCert }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $domain }}-ca
  namespace: {{ $ns }}
  labels:
    app.kubernetes.io/name: {{ include "educates.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  ca.crt: {{ $caCert | b64enc }}
{{- end }}
