{{- $opNs := include "educates.operator.namespace" . -}}

{{- $ingressSecretName := .Values.clusterIngress.tlsCertificateRef.name -}}
{{- $ingressSecretNs := .Values.clusterIngress.tlsCertificateRef.namespace -}}
{{- $ingressCaSecretName := .Values.clusterIngress.caCertificateRef.name -}}
{{- $ingressCaSecretNs := .Values.clusterIngress.caCertificateRef.namespace -}}

{{- $hasIngressSecret := and $ingressSecretName $ingressSecretNs (ne $ingressSecretNs $opNs) -}}
{{- $hasIngressCaSecret := and $ingressCaSecretName $ingressCaSecretNs (ne $ingressCaSecretNs $opNs) -}}

{{- if or $hasIngressSecret $hasIngressCaSecret }}
---
apiVersion: secrets.educates.dev/v1beta1
kind: SecretCopier
metadata:
  name: educates-ingress-secrets
  labels:
    app.kubernetes.io/name: {{ include "educates.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  rules:
  {{- if $hasIngressSecret }}
  - sourceSecret:
      name: {{ $ingressSecretName }}
      namespace: {{ $ingressSecretNs }}
    targetNamespaces:
      nameSelector:
        matchNames:
        - {{ $opNs }}
  {{- end }}
  {{- if $hasIngressCaSecret }}
  - sourceSecret:
      name: {{ $ingressCaSecretName }}
      namespace: {{ $ingressCaSecretNs }}
    targetNamespaces:
      nameSelector:
        matchNames:
        - {{ $opNs }}
  {{- end }}
{{- end }}

{{- $externalPullSecrets := include "educates.externalImagePullSecrets" . | fromJson -}}
{{- $validPullSecrets := list -}}
{{- if eq (kindOf $externalPullSecrets) "slice" }}
{{- range $externalPullSecrets }}
{{- if eq (kindOf .) "map" }}
{{- $validPullSecrets = append $validPullSecrets . -}}
{{- end }}
{{- end }}
{{- end }}
{{- if $validPullSecrets }}
---
apiVersion: secrets.educates.dev/v1beta1
kind: SecretCopier
metadata:
  name: educates-upstream-image-pull-secrets
  labels:
    app.kubernetes.io/name: {{ include "educates.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  rules:
  {{- range $validPullSecrets }}
  - sourceSecret:
      name: {{ index . "name" }}
      namespace: {{ index . "namespace" }}
    targetNamespaces:
      nameSelector:
        matchNames:
        - {{ $opNs }}
  {{- end }}
{{- end }}

{{- $pullSecretNames := include "educates.imagePullSecretNames" . | fromJson -}}
{{- if and $pullSecretNames (eq (kindOf $pullSecretNames) "slice") (gt (len $pullSecretNames) 0) }}
---
apiVersion: secrets.educates.dev/v1beta1
kind: SecretCopier
metadata:
  name: educates-downstream-image-pull-secrets
  labels:
    app.kubernetes.io/name: {{ include "educates.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  rules:
  {{- range $pullSecretNames }}
  - sourceSecret:
      name: {{ . }}
      namespace: {{ $opNs }}
    targetNamespaces:
      labelSelector:
        matchLabels:
          training.educates.dev/component: portal
  - sourceSecret:
      name: {{ . }}
      namespace: {{ $opNs }}
    targetNamespaces:
      labelSelector:
        matchLabels:
          training.educates.dev/component: environment
  {{- end }}
{{- end }}

{{- $externalThemeDataRefs := include "educates.externalThemeDataRefs" . | fromJson -}}
{{- $validThemeRefs := list -}}
{{- if eq (kindOf $externalThemeDataRefs) "slice" }}
{{- range $externalThemeDataRefs }}
{{- if eq (kindOf .) "map" }}
{{- $validThemeRefs = append $validThemeRefs . -}}
{{- end }}
{{- end }}
{{- end }}
{{- if $validThemeRefs }}
---
apiVersion: secrets.educates.dev/v1beta1
kind: SecretCopier
metadata:
  name: educates-upstream-website-themes
  labels:
    app.kubernetes.io/name: {{ include "educates.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  rules:
  {{- range $validThemeRefs }}
  - sourceSecret:
      name: {{ index . "name" }}
      namespace: {{ index . "namespace" }}
    targetNamespaces:
      nameSelector:
        matchNames:
        - {{ $opNs }}
  {{- end }}
{{- end }}
