{{- $smImage := include "educates.image" (dict "name" "secrets-manager" "context" .) }}
{{- $pullPolicy := include "educates.imagePullPolicy" $smImage }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: secrets-manager
  namespace: {{ include "educates.operator.namespace" . }}
  labels:
    app.kubernetes.io/name: {{ include "educates.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    deployment: secrets-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: secrets-manager
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        deployment: secrets-manager
        app.kubernetes.io/name: {{ include "educates.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      serviceAccountName: secrets-manager
      automountServiceAccountToken: false
      {{- with .Values.clusterSecrets.pullSecretRefs }}
      imagePullSecrets:
        {{- range . }}
        - name: {{ .name }}
        {{- end }}
      {{- end }}
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
      containers:
      - name: operator
        image: {{ $smImage }}
        imagePullPolicy: {{ $pullPolicy }}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop: ["ALL"]
        startupProbe:
          initialDelaySeconds: 15
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 4
          httpGet:
            path: /healthz?probe=startup
            port: 8080
        livenessProbe:
          initialDelaySeconds: 15
          periodSeconds: 30
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
          httpGet:
            path: /healthz?probe=liveness
            port: 8080
        volumeMounts:
        - name: config
          mountPath: /opt/app-root/config/
        - name: token
          mountPath: /var/run/secrets/kubernetes.io/serviceaccount
          readOnly: true
      volumes:
      - name: config
        secret:
          secretName: educates-config
      - name: token
        secret:
          secretName: secrets-manager-token
