apiVersion: v1
kind: ServiceAccount
metadata:
  name: session-manager
  namespace: {{ include "educates.operator.namespace" . }}
  labels:
    app.kubernetes.io/name: {{ include "educates.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: image-puller
  namespace: {{ include "educates.operator.namespace" . }}
  labels:
    app.kubernetes.io/name: {{ include "educates.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: secrets-manager
  namespace: {{ include "educates.operator.namespace" . }}
  labels:
    app.kubernetes.io/name: {{ include "educates.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
