apiVersion: v1
kind: Secret
metadata:
  name: default-website-theme
  namespace: {{ include "educates.operator.namespace" . }}
  labels:
    app.kubernetes.io/name: {{ include "educates.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  workshop-dashboard.html: {{ .Values.websiteStyling.workshopDashboard.html | default "" | b64enc }}
  workshop-dashboard.js: {{ .Values.websiteStyling.workshopDashboard.script | default "" | b64enc }}
  workshop-dashboard.css: {{ .Values.websiteStyling.workshopDashboard.style | default "" | b64enc }}
  workshop-instructions.html: {{ .Values.websiteStyling.workshopInstructions.html | default "" | b64enc }}
  workshop-instructions.js: {{ .Values.websiteStyling.workshopInstructions.script | default "" | b64enc }}
  workshop-instructions.css: {{ .Values.websiteStyling.workshopInstructions.style | default "" | b64enc }}
  workshop-started.html: {{ .Values.websiteStyling.workshopStarted.html | default "" | b64enc }}
  workshop-finished.html: {{ .Values.websiteStyling.workshopFinished.html | default "" | b64enc }}
  training-portal.html: {{ .Values.websiteStyling.trainingPortal.html | default "" | b64enc }}
  training-portal.js: {{ .Values.websiteStyling.trainingPortal.script | default "" | b64enc }}
  training-portal.css: {{ .Values.websiteStyling.trainingPortal.style | default "" | b64enc }}
