#@ load("@ytt:data", "data")
#@ load("@ytt:overlay", "overlay")
#@ load("@ytt:assert", "assert")

#@ (hasWorkloadIdentityCertManager, _) = assert.try_to(lambda: len(data.values["clusterInfrastructure"]["gcp"]["workloadIdentity"]["cert-manager"]) > 0)

#@ if hasWorkloadIdentityCertManager:
#@   certManagerWorkloadIdentity = data.values["clusterInfrastructure"]["gcp"]["workloadIdentity"]["cert-manager"]
#@ else:
#@   fail("cert-manager is enabled and can not be configured. Missing workloadIdentity")
#@ end

#@overlay/match-child-defaults missing_ok=True
clusterPackages:
  cert-manager:
    enabled: true
    settings:
      serviceaccount:
        annotations:
          iam.gke.io/gcp-service-account: #@ certManagerWorkloadIdentity
