#@ load("@ytt:data", "data")
#@ load("@ytt:overlay", "overlay")

#@overlay/match-child-defaults missing_ok=True
clusterPackages:
  contour:
    enabled: true
    settings:
      infraProvider: gcp
      configFileContents:
        defaultHttpVersions:
          - "HTTP/1.1"
      service:
        type: LoadBalancer
      externaldns:
        domains:
          -  #@ data.values.clusterIngress.domain
