apiVersion: kapp.k14s.io/v1alpha1
kind: Config
rebaseRules:
  - paths:
      - [spec, selector, matchLabels]
    type: copy
    sources: [existing, new]
    resourceMatchers:
      - apiVersionKindMatcher: { apiVersion: apps/v1, kind: DaemonSet }
      - apiVersionKindMatcher: { apiVersion: apps/v1, kind: Deployment }
  - paths:
      - [spec, selector]
    type: copy
    sources: [existing, new]
    resourceMatchers:
      - apiVersionKindMatcher: { apiVersion: v1, kind: Service }
      - apiVersionKindMatcher: { apiVersion: apps/v1, kind: Deployment }
