apiVersion: training.educates.dev/v1beta1
kind: Workshop
metadata:
  name: "{{ .WorkshopName }}"
spec:
  title: "{{ or .WorkshopTitle "Workshop" }}"
  description: "{{ or .WorkshopDescription "Workshop description." }}"
  publish:
    image: "$(image_repository)/{{ .WorkshopName }}-files:$(workshop_version)"
  workshop:
    {{- if .WorkshopImage }}
    image: "{{ .WorkshopImage }}"
    {{- end }}
    files:
    - image:
        url: "$(image_repository)/{{ .WorkshopName }}-files:$(workshop_version)"
      includePaths:
      - /workshop/**
      - /exercises/**
      - /README.md
  session:
    namespaces:
      budget: medium
      security:
        token:
          enabled: {{ .WithKubernetesAccess }}      
    applications:
      {{- if eq .WithWorkshopInstructions "false"}}
      workshop:
        enabled: {{ .WithWorkshopInstructions }}
      {{- end }}
      terminal:
        enabled: {{ .WithTerminal }}
        {{- if eq .WithTerminal "true" }}
        layout: split
        {{- end }}
      editor:
        enabled: {{ .WithEditor }}
      console:
        enabled: {{ .WithConsole }}
      docker:
        enabled: {{ .WithDocker }}
      registry:
        enabled: {{ .WithRegistry }}
      vcluster:
        enabled: {{ .WithVirtualCluster }}
