#@ load("@ytt:data", "data")

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: educates-session-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: educates-session-manager
subjects:
- kind: ServiceAccount
  name: session-manager
  namespace: #@ data.values.operator.namespace

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: educates-session-manager:admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
- kind: ServiceAccount
  name: session-manager
  namespace: #@ data.values.operator.namespace

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: educates-session-manager:kyverno-policies
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kyverno:rbac:admin:policies
subjects:
- kind: ServiceAccount
  name: session-manager
  namespace: #@ data.values.operator.namespace

#@ if data.values.sessionManager.clusterAdmin:
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: educates-session-manager:cluster-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: session-manager
  namespace: #@ data.values.operator.namespace
#@ end

#@ if data.values.clusterSecurity.policyEngine == "pod-security-policies":
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: educates-session-manager-psp
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: educates-baseline-psp
subjects:
- kind: ServiceAccount
  name: session-manager
  namespace: #@ data.values.operator.namespace

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: educates-image-puller-psp
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: educates-baseline-psp
subjects:
- kind: ServiceAccount
  name: image-puller
  namespace: #@ data.values.operator.namespace
#@ end

#@ if data.values.clusterSecurity.policyEngine == "security-context-constraints":
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: educates-session-manager-scc
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: educates-baseline-scc
subjects:
- kind: ServiceAccount
  name: session-manager
  namespace: #@ data.values.operator.namespace

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: educates-image-puller-scc
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: educates-baseline-scc
subjects:
- kind: ServiceAccount
  name: image-puller
  namespace: #@ data.values.operator.namespace
#@ end
