---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: educateswildcard
spec:
  secretName: educateswildcard
  issuerRef:
    name: educateswildcard
    kind: ClusterIssuer
  dnsNames:
    - REPLACE_ME
