---
apiVersion: kbld.k14s.io/v1alpha1
minimumRequiredVersion: 0.30.0
kind: Config
searchRules:
  - keyMatcher:
      name: SESSION_MANAGER_IMAGE
  - keyMatcher:
      name: SECRETS_MANAGER_IMAGE
  - keyMatcher:
      name: TUNNEL_MANAGER_IMAGE
  - keyMatcher:
      name: TRAINING_PORTAL_IMAGE
  - keyMatcher:
      name: DOCKER_IN_DOCKER_IMAGE
  - keyMatcher:
      name: DOCKER_REGISTRY_IMAGE
  - keyMatcher:
      name: PAUSE_CONTAINER_IMAGE
  - keyMatcher:
      name: BASE_ENVIRONMENT_IMAGE
  - keyMatcher:
      name: JDK8_ENVIRONMENT_IMAGE
  - keyMatcher:
      name: JDK11_ENVIRONMENT_IMAGE
  - keyMatcher:
      name: CONDA_ENVIRONMENT_IMAGE
